// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btevtyamuxysdmenjsdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZXZ0eWFtdXh5c2RtZW5qc2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NTkzNjYsImV4cCI6MjA3ODEzNTM2Nn0.OAthz4oXewZpelvEn-ogSmpWW6q6o6erBGeRJJSzAwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});